bookSearch/urls.py
from django.urls import path
from . import views

app_name = 'bookSearch'

urlpatterns = [
    path('', views.showFinder, name='showFinder'),
    path('getLikes/<str:bookID>', views.getLikes, name='getLikes'),
    path('addLike/', views.addLike, name='addLike'),
    path('mostLiked/', views.mostLiked, name='mostLiked')
]

logInAndGreet/urls.py
from django.urls import path
from . import views

app_name = 'logInAndGreet'

urlpatterns = [
    path('', views.logInAndGreetIndex, name='logInAndGreetIndex'),
    path('logout/', views.logOutAcc, name='logOutAcc'),
    path('signup/', views.signUpAcc, name='signUpAcc')
]

story9/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bookSearch.urls')),
    path('login/', include('logInAndGreet.urls'))
]

bookSearch/models.py
from django.db import models

# Create your models here.
class LikedBooks(models.Model):
    bookID = models.CharField(max_length=150)
    title = models.CharField(max_length=150)
    thumbnail = models.URLField()
    description = models.TextField()
    likes = models.IntegerField(default=1)

    def __str__(self):
        return self.title

logInAndGreet/models.py
from django.db import models

# Create your models here.

logInAndGreet/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'text',
        'title': 'Username',
        'placeholder': 'Username',
        'required': True,
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type': 'password',
        'placeholder': 'Password',
        'required': True,
    }))

bookSearch/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.core import serializers

from .models import LikedBooks

# Create your views here.
def showFinder(request):
    return render(request, 'index.html')

def getLikes(request, bookID):
    try:
        bookTarget = LikedBooks.objects.get(bookID = bookID)
        return JsonResponse({"likes" : bookTarget.likes})
    except:
        return JsonResponse({"likes" : 0})

def addLike (request):
    if request.method == "POST":
        bookID = request.POST["bookID"]
        
        try:
            bookTarget = LikedBooks.objects.get(bookID = bookID)
            bookTarget.likes += 1
            bookTarget.save()
        except:
            LikedBooks.objects.create (
                bookID = request.POST["bookID"],
                title = request.POST["title"],
                thumbnail = request.POST["thumbnail"],
                description = request.POST["description"]
            )
    
    return redirect ("bookSearch:showFinder")

def mostLiked(request):
    return JsonResponse({"topBooks" : list(LikedBooks.objects.order_by("-likes")[:5].values())})

logInAndGreet/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout

from .forms import LoginForm


# Create your views here.

def logInAndGreetIndex(request):
    if (request.method == 'POST'):
        form = LoginForm(request.POST)
        
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if (user is not None):
                login(request, user)
                return redirect('/login/')
                
            else:
                messages = ['Incorrect username or password']
                response = {'form': form, 'messages': messages}
                return render(request, 'login.html', response)

    else:
        form = LoginForm()
        response = {'form': form}
        return render(request, 'login.html', response)

def logOutAcc(request):
    logout(request)
    return redirect('/login')

def signUpAcc(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/login/')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})

bookSearch/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>BookFinder</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <style>
        body {
            background-color: #162447;
            color: white;
        }

        .bookCard {
            background-color: #1b1b2f;
            border-radius: 15px;
            transition: all 0.2s;
        }

        .bookCard:hover {
            background-color: #1f4068;
        }

        .modal-body, .modal-header, .modal-footer {
            background-color: black;
        }
    </style>
</head>
<body>
    
    <div class="header container">
        <div class="d-flex justify-content-center">
            <h1>Welcome to BookFinder!</h1>
        </div>

        <div class="container d-flex">
            <input type="text" class="form-control" id="searchBox" placeholder="search">
            <div class="buffer" style="width: 50px;"></div>
            <button class="btn btn-success" id="searchButton">Search</button>
        </div>
        <div class="buffer2" style="height: 50px;"></div>
        <div class="d-flex justify-content-center">
            <button type="button" class="btn btn-primary topButton" data-toggle="modal" data-target="#exampleModal">
                Top 5 books!
            </button>
        </div>
    </div>

    
    
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Most liked books below!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-body" id="topList">

            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
        </div>
    </div>

    <div class="buffer2" style="height: 100px;"></div>

    <div class="bookList container">
        <h5>Empty list :(</h5>
    </div>
    

    <script>
        $(document).ready(function() {
            $("#searchButton").click(function() {
                var searchedBooks = $("#searchBox").val();
                console.log("Searched title : " + searchedBooks)
                
                if (searchedBooks == "") {
                    alert("Invalid name!")
                } else {
                    $(".bookList").empty();

                    $.get (`https://www.googleapis.com/books/v1/volumes?q=${searchedBooks}`, function(data) {
                        var bookListDiv = $(".bookList");

                        for (var book of data.items) {
                            console.log(book.volumeInfo.title);

                            var title = book.volumeInfo.title;
                            var publishDate = book.volumeInfo.publishedDate;
                            if (publishDate == undefined) {
                                publishDate = 'Publish date is not available';
                            }
                            var thumbnail = book.volumeInfo.imageLinks.thumbnail;
                            var description = book.volumeInfo.description;
                            if (description == undefined) {
                                description = 'No description available for this book'
                            }
                            var likes
                            $.ajax({
                                type : 'GET',
                                url : `getLikes/${book.id}`,
                                async : false,
                                success : function(bookTarget) {
                                    likes = bookTarget.likes
                                    console.log(likes)

                                    console.log("Likes update2: " + likes)
                                    bookListDiv.append (
                                        `<div class="d-flex bookCard" style="padding: 15px">
                                            <img src="${thumbnail}" height="195px" width="128px" style="margin: 0 30px 0 0">
                                            <div>
                                                <h4>${title}</h4>
                                                <h6>${publishDate}</h6>
                                                <p>${description}</p>
                                                <button class="btn btn-danger likeButton" bookID="${book.id}" title="${title}" thumbnail="${thumbnail}" description="${description}">Like!</button>
                                                <p class="likeCounter">Like(s) : ${likes}</p>
                                            </div>
                                        </div>
                                        <div style="height: 50px;"></div>`
                                    )  
                                }

                            })                       
                        }
                    });
                }
            });

            $(".bookList").click(function (event) {
                bookTarget = event.target
                if ($(bookTarget).hasClass("likeButton")) {
                    var bookID = $(bookTarget).attr("bookID")
                    var title = $(bookTarget).attr("title")
                    var thumbnail = $(bookTarget).attr("thumbnail")
                    var description = $(bookTarget).attr("description")
                    console.log("Book liked: " + title)

                    $.post("{% url 'bookSearch:addLike' %}", {
                        csrfmiddlewaretoken : "{{csrf_token}}",
                        title : title,
                        bookID : bookID,
                        thumbnail : thumbnail,
                        description : description
                    }).done(function() {
                        $.get(`/getLikes/${bookID}`, function(book) {
                            $(bookTarget).next().text(`Like(s) : ${book.likes}`)
                        })
                    })
                }
            });

            $(".topButton").click(function() {
                $("#topList").empty();
                $.get("{% url 'bookSearch:mostLiked' %}", function(data) {
                    for (var topB of data.topBooks) {
                        console.log("masuk 2")
                        $("#topList").append(
                            `<div class="d-flex">
                                <img src="${topB.thumbnail}" height="195px" width="128px" style="margin: 0 30px 0 0">
                                    <div>
                                        <h4>${topB.title}</h4>
                                        <h6>${topB.publishDate}</h6>
                                        <p>${topB.description}</p>
                                        <h6>Like(s) : ${topB.likes}</h6>
                                    </div>
                            </div>
                            <div style="height: 50px;"></div>`
                        )
                    }
                })
            })

        })
    </script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
</body>
</html>

logInAndGreet/templates/login.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Greetings!</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'loginStyle.css' %}">

</head>
<body>
    {% if user.is_authenticated %}
    <div class="cardBox">
        <div class="greet">
            <h5>Hello</h5>
            <h1 id="username">{{user.username}}</h1>
            <h5>Have a nice day!</h5>
        </div>
        <a href="{% url 'logInAndGreet:logOutAcc' %}">
            <button class="btn btn-danger" id="logoutButton">Log Out</button>
        </a>
    </div>
        
    {% else %}
        <div class="form container">
            <form method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success" id="loginButton">Log In</button>
            </form>
            {% if messages %}
            {% for message in messages %}
                <p id="errorMessage">{{ message }}</p>
            {% endfor %}
            {% endif %}

            <a href="{% url 'logInAndGreet:signUpAcc' %}">
                <button class="btn btn-link" id="signupButton">Sign Up</button>
            </a>
        </div>
    {% endif %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

logInAndGreet/templates/signup.html
{% load crispy_forms_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up!</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'loginStyle.css' %}">

</head>
<body>
    <div class="signupForm container">
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                {{ field|as_crispy_field }}
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary" id="signupCreateButton">Sign up!</button>
        </form>
    </div>
       

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>